### ISSUE TITLE
Wrong GID applied to folder

### ISSUE THREAD

**Issue by sdotb** [Gronis/docker-seafile-client#13]
Set up in docker-compose.yml:
```
      - SEAFILE_UID=0
      - SEAFILE_GID=100
 ```
on machine sysadmins group have GID 1000, users group have GID 100

what I expect:
drwxrwsr-x+  2 root users  4096 Feb 26 12:02 test-folder

what I found:
drwxrwsr-x+  2 root sysadmins  4096 Feb 26 12:02 test-folder

UID changes are reflected correctly, GID no.

**Comment by Gronis** [comment]
I've made some changes that works for me. Try out the latest pull from docker hub!

**Comment by sdotb** [comment]
Looks like it work as expected now
